### ISSUE TITLE
Error running the example

### ISSUE THREAD

**Issue by iteimouri** [bblais/pyndamics#2]
I'm trying to run pyndamics/examples/MCMC Examples.ipynb, I have individually copied and pasted the simulation.py and mcmc.py, yet I get an error running `model = MCMCModel(sim,{'b':[0,10]})`. The error raised from simulation.py I wonder where is the issue? 
<img width="723" alt="Screenshot 2020-04-01 at 02 05 23" src="https://user-images.githubusercontent.com/29966416/78088823-44e39480-73bd-11ea-97f7-f0a40fff6ca1.png">

**Comment by bblais** [comment]
My guess is that pymc has changed so much in the intervening years, that there are conflicts.  I moved all of the examples to emcee.  Check out Emcee Examples.ipynb and see if you still have issues.

btw, a good way to install is:

pip install "git+git://github.com/bblais/pyndamics" --upgrade

let me know how it goes!

**Comment by iteimouri** [comment]
Thank you for getting back to me. So when I run` !pip install "git+git://github.com/bblais/pyndamics" --upgrade` (the "!" is due to the fact that I am using Google Colab) despiting installing pyndamics-0.0.8 successfully, when I run Emcee Examples.ipynb I get ModuleNotFoundError: No module named 'emcee' from 
```
from pyndamics import Simulation
from pyndamics.emcee import *
```
not sure if the files are linked correctly? This is why I was copy-pasting them before.

**Comment by bblais** [comment]
Emcee is a separate package.    Can be installed with
  

  
pip install emcee
  

  
Hope this helps!
  

  
  

  
  
>

**Comment by iteimouri** [comment]
Thanks now it works up to the model again, when I run from 
`model=MCMCModel(sim,b=Uniform(0,10))` from [here.](https://github.com/bblais/pyndamics/blob/master/examples/Emcee%20Examples.ipynb)
I get the following:
<img width="787" alt="Screenshot 2020-04-01 at 03 03 57" src="https://user-images.githubusercontent.com/29966416/78091762-c0e1da80-73c5-11ea-8ce9-feada7a175b2.png">

**Comment by bblais** [comment]
Now, that’s a real error — the fact I can’t spell.  :-)

I just updated it, so you can run the 

!pip install "git+git://github.com/bblais/pyndamics <git+git://github.com/bblais/pyndamics>" —upgrade


- Brian

**Comment by iteimouri** [comment]
Thank you Brian, now it works :)

**Comment by bblais** [comment]
great!  let me know how it goes, any improvements, what you like/dislike, etc....
